#服务端口
server:
  port: 18080
spring:
  application:
    name: tanhua-app-server
  redis:  #redis配置
    port: 6379
    host: 192.168.136.160
  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
  rabbitmq:
    host: 192.168.136.160
    port: 5672
    username: guest
    password: guest
dubbo:    #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
tanhua:
  #默认推荐列表
  default:
    recommend:
      users: 2,3,8,10,18,20,24,29,27,32,36,37,56,64,75,88
  sms:
    signName: 大洲
    templateCode: SMS_461855349
    accessKey: LTAI5t6mxq4iah9AfrXLGyWK
    secret: AFeDlLcU5d5cxzCitHIq9x8wLjoGRf
  oss:
    accessKey: LTAI5tGBPNsnGPrFm1FbfMwW
    secret: DyughXRNJ1ryyzCQNjEVRORI2WoYku
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucketName: dazhou123
    url: https://dazhou123.oss-cn-guangzhou.aliyuncs.com/
  aip:
    appId: 36050788
    apiKey: nIUw5C5qa9Lur6m8a5ohdf2X
    secretKey: YTG2qiWAGosq8EgIZSxACnzLDSNawGUF
  huanxin:
    appkey: 1146230717209533#weixiao
    clientId: YXA67561g31JQxmh2UoPESFe8g
    clientSecret: YXA6F-YVOpHCaozTYoO-JhhI9x3rqBc
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个
  tracker-list: 192.168.136.160:22122
  web-server-url: http://192.168.136.160:8888/
Spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB